theme: jekyll-theme-cayman
title: "An ETL data pipeline with Pyspark, Apache Airflow and BI dashboard using Apache Superset"
description: "This project demostrated an end to end pipeline by applying spark parallel processing to process large dataset coming in different format and integrating with different datawarehouse technologies and visualizing data using Superset"
author: "Jude Leonard"

url: 'https://judeleonard.github.io/'
baseurl: 'Prescriber-ETL-data-pipeline/'
